services:
  - name: flood-prediction-api
    type: web
    env: python
    buildCommand: pip install -r predictor/requirements.txt
    startCommand: python api-handler/api_handler.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: "5000"
    plan: free
    region: oregon

staticSites:
  - name: flood-prediction-website
    buildCommand: ""
    publishPath: website
    plan: free
